env:
  global:
    - CC_TEST_REPORTER_ID=ff6e5b48c72dde10ea083d8b77837d8a98ce484645e9bc30645d67e06f4a0cf1
language: php
php:
  - '7.1'
  - '7.2'
  - '7.3'
  - hhvm # on Trusty only
  - nightly
before_script:
  - if [[ "$TRAVIS_PHP_VERSION" == "7.1" ]]; then PHPUNIT_FLAGS="--coverage-clover build/logs/clover.xml"; fi
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
script:
  - composer install --prefer-dist --no-interaction
  - vendor/bin/phpunit test/ $PHPUNIT_FLAGS --configuration travis.phpunit.xml
after_script:
  - if [[ "$TRAVIS_PHP_VERSION" == "7.1" ]]; then ./cc-test-reporter after-build -t clover --exit-code $TRAVIS_TEST_RESULT; fi